// GENERATED FILE - do not edit by hand.
// Run `npm run sync:ingredients` to refresh, then commit the result.
// Source: https://www.themealdb.com/api/json/v1/1/list.php?i=list (TheMealDB, public test key).

/**
 * Static autocomplete and spell-check source for the ingredient input. Shipped
 * in the bundle on purpose: the generator must stay usable without a backend
 * round trip, so nothing here is fetched at runtime.
 */
export const INGREDIENT_NAMES: readonly string[] = [
  'Achiote paste', 'Achiote seeds', 'Ackee', 'Alinos sauce', 'All purpose flour',
  'All-purpose seasoning', 'Allspice', 'Allspice berries', 'Almond essence', 'Almond extract',
  'Almond flour', 'Almond milk', 'Almond paste', 'Almonds', 'Ancho chillies', 'Anchovy fillet',
  'Apple', 'Apple cider vinegar', 'Apples', 'Appleton rum', 'Apricot', 'Apricot jam', 'Arabic rice',
  'Asparagus', 'Aubergine', 'Avacado hass pulp', 'Avocado', 'Baby aubergine', 'Baby lettuce leaves',
  'Baby new potatoes', 'Baby pak koi', 'Baby plum tomatoes', 'Baby spinach', 'Baby squid', 'Bacon',
  'Bacon lardon', 'Baguette', 'Baked beans', 'Baking powder', 'Balsamic vinegar', 'Bamboo shoot',
  'Banana', 'Banana leaves', 'Banana pepper', 'Barbeque sauce', 'Barramundi', 'Basil',
  'Basil leaves', 'Basmati rice', 'Bay leaf', 'Bay leaves', 'Bean sprouts', 'Beef', 'Beef brisket',
  'Beef cutlet', 'Beef fillet', 'Beef flank steak', 'Beef gravy', 'Beef kidney', 'Beef mince',
  'Beef shin', 'Beef shoulder', 'Beef stock', 'Beef stock concentrate', 'Beef stock cubes',
  'Beef tenderloin', 'Beef tomatoes', 'Beer', 'Beetroot', 'Beets', 'Bell pepper',
  'Bicarbonate of soda', 'Birds-eye chillies', 'Biryani masala', 'Black beans',
  'Black cardamom pods', 'Black eyed peas', 'Black olives', 'Black pepper', 'Black pudding',
  'Black treacle', 'Blackberries', 'Blackcurrant jam', 'Blue food colouring', 'Blueberries',
  'Boiling water', 'Bok choi', 'Borlotti beans', 'Bouillon cubes', 'Bouquet garni', 'Bowtie pasta',
  'Braeburn apples', 'Bramley apples', 'Brandy', 'Bread', 'Bread flour', 'Bread rolls',
  'Breadcrumbs', 'Breadfruit', 'Brie', 'Broad beans', 'Broccoli', 'Brown lentils', 'Brown rice',
  'Brown rice noodle', 'Brown sugar', 'Brussels sprouts', 'Bryndza cheese', 'Buckwheat',
  'Buckwheat flour', 'Bulgur wheat', 'Bun', 'Buns', 'Butter', 'Butter beans', 'Buttermilk',
  'Butternut squash', 'Cabbage', 'Cabbage leaves', 'Cacao', 'Cafe la llave', 'Cajun', 'Callaloo',
  'Can of chickpeas', 'Candied peel', 'Canned beans', 'Canned tomatoes', 'Cannellini beans',
  'Canola oil', 'Capers', 'Caramel', 'Caramel sauce', 'Caramelized sugar sauce', 'Caraway seed',
  'Cardamom', 'Carrot', 'Carrots', 'Casabe', 'Cashew nuts', 'Cashews', 'Cassaba', 'Cassava',
  'Cassava flour', 'Caster sugar', 'Cauliflower', 'Cayenne pepper', 'Celeriac', 'Celery',
  'Celery salt', 'Challots', 'Charlotte potatoes', 'Cheddar', 'Cheddar cheese', 'Cheese',
  'Cheese curds', 'Cheese slices', 'Cherry', 'Cherry tomatoes', 'Chestnut mushroom', 'Chestnuts',
  'Chicken', 'Chicken bouillon powder', 'Chicken breast', 'Chicken breasts', 'Chicken drumsticks',
  'Chicken legs', 'Chicken liver', 'Chicken stock', 'Chicken stock concentrate',
  'Chicken stock cube', 'Chicken thighs', 'Chicken wings', 'Chickpea flour', 'Chickpeas',
  'Chili flakes', 'Chili powder', 'Chilled butter', 'Chilli', 'Chilli bean paste', 'Chilli flakes',
  'Chilli powder', 'Chilli sauce', 'Chimichurri sauce', 'Chinese broccoli', 'Chinese cabbage',
  'Chinese five spice powder', 'Chinese leaf', 'Chinese long beans', 'Chinese sesame sauce',
  'Chives', 'Chocolate chips', 'Chopped chive', 'Chopped onion', 'Chopped parsley',
  'Chopped tomatoes', 'Chorizo', 'Christmas pudding', 'Chuck roast', 'Ciabatta', 'Cider',
  'Cider vinegar', 'Cilantro', 'Cilantro leaves', 'Cinnamon', 'Cinnamon stick', 'Clams',
  'Clear honey', 'Clotted cream', 'Cloves', 'Coarse salt', 'Coco sugar', 'Cocoa', 'Cocoa powder',
  'Coconut', 'Coconut cream', 'Coconut flakes', 'Coconut milk', 'Coconut oil', 'Cocoy banana',
  'Cod', 'Codfish bulljaw', 'Colby jack cheese', 'Cold water', 'Conchs', 'Condensed milk',
  'Cooked beetroot', 'Cooked chestnut', 'Cooking apples', 'Cooking wine', 'Coriander',
  'Coriander leaves', 'Coriander seeds', 'Corn flour', 'Corn on the cob', 'Corn tortillas',
  'Corned beef', 'Cornmeal', 'Cornstarch', 'Cottage cheese', 'Courgettes', 'Couscous', 'Crab meay',
  'Cranberry', 'Cream', 'Cream cheese', 'Cream of tartar', 'Creamed corn', 'Creme fraiche',
  'Crusty bread', 'Cuban bread', 'Cubed feta cheese', 'Cucumber', 'Cumin', 'Cumin seeds',
  'Currants', 'Curry powder', 'Custard', 'Custard powder', 'Daikon radish', 'Dark beer',
  'Dark brown soft sugar', 'Dark brown sugar', 'Dark chocolate', 'Dark chocolate chips', 'Dark rum',
  'Dark soft brown sugar', 'Dark soy sauce', 'Date molasses', 'Deli ham', 'Demerara sugar',
  'Desiccated coconut', 'Dessert rice', 'Diced tomatoes', 'Digestive biscuits', 'Dijon mustard',
  'Dill', 'Dill pickles', 'Doner meat', 'Doubanjiang', 'Double cream', 'Dried apricots',
  'Dried cherries', 'Dried chillies', 'Dried cranberries', 'Dried dill', 'Dried fruit',
  'Dried mint', 'Dried oregano', 'Dried red chillies', 'Dried shrimp', 'Dried sorrel',
  'Dried white beans', 'Dried white corn', 'Dried white navy beans', 'Dry sherry', 'Dry white wine',
  'Duck', 'Duck fat', 'Duck legs', 'Duck sauce', 'Dulce de leche', 'Dutch stroop', 'Egg',
  'Egg noodles', 'Egg plants', 'Egg roll wrappers', 'Egg rolls', 'Egg wash', 'Egg white',
  'Egg yolks', 'Eggs', 'Emmentaler cheese', 'Enchilada sauce', 'English muffins', 'English mustard',
  'Evaporated milk', 'Extra virgin olive oil', 'Fajita seasoning', 'Falafel', 'Farfalle', 'Farine',
  'Farmers cheese', 'Fast action yeast', 'Feather blade beef', 'Fennel', 'Fennel bulb',
  'Fennel seeds', 'Fenugreek', 'Fermented black beans', 'Feta', 'Fettuccine', 'Fideo', 'Figs',
  'Fillet of steak', 'Filo pastry', 'Fine yellow cornmeal', 'Fish fillet', 'Fish sauce',
  'Fish seasoning', 'Fish stock', 'Five spice powder', 'Flaked almonds', 'Flank steak',
  'Flat rice noodles', 'Flax eggs', 'Flour', 'Flour tortilla', 'Floury potatoes',
  'Free-range egg, beaten', 'Free-range eggs, beaten', 'Freekeh', 'French lentils', 'Fresh basil',
  'Fresh thyme', 'Freshly chopped parsley', 'Fried ripe bananas', 'Fries', 'Frogs legs',
  'Fromage frais', 'Frozen mixed berries', 'Frozen peas', 'Frozen seafood mix', 'Fruit mix',
  'Full fat sour cream', 'Full fat yogurt', 'Galangal', 'Galangal paste', 'Garam masala', 'Garlic',
  'Garlic bulb', 'Garlic clove', 'Garlic granules', 'Garlic powder', 'Garlic sauce',
  'Gelatine leafs', 'German sausages', 'Ghee', 'Gherkin relish', 'Ginger', 'Ginger cordial',
  'Ginger garlic paste', 'Ginger paste', 'Gingerbread spice', 'Glace cherry', 'Glutinous rice',
  'Goat meat', 'Goats cheese', 'Gochujang', 'Golden caster sugar', 'Golden syrup', 'Goose fat',
  'Gouda cheese', 'Graham cracker crumbs', 'Grand marnier', 'Granulated sugar', 'Grape leaves',
  'Grape nut cereal', 'Grape tomatoes', 'Grapefruit', 'Great northern beans', 'Greek yogurt',
  'Green beans', 'Green cardamom pods', 'Green chilli', 'Green olives', 'Green papaya',
  'Green pepper', 'Green red lentils', 'Green salsa', 'Grits', 'Ground allspice', 'Ground almonds',
  'Ground annatto', 'Ground beef', 'Ground black pepper', 'Ground cardomom', 'Ground chicken',
  'Ground cinnamon', 'Ground clove', 'Ground coriander', 'Ground cumin', 'Ground ginger',
  'Ground mahleb', 'Ground mustard', 'Ground nut oil', 'Ground nutmeg', 'Ground oats',
  'Ground onion', 'Ground pistachios', 'Ground poppy seeds', 'Ground pork', 'Ground sugar',
  'Ground turmeric', 'Ground walnuts', 'Gruyère', 'Habanero pepper', 'Haddock', 'Hail', 'Hake',
  'Ham', 'Hard taco shells', 'Haricot beans', 'Harissa spice', 'Hazlenuts', 'Heavy cream',
  'Herring', 'High heat cooking oil', 'Hind shank', 'Hoisin sauce', 'Honey', 'Horseradish',
  'Hot beef stock', 'Hot chilli powder', 'Hot mint', 'Hot smoked flaked salmon',
  'Hot smoked paprika', 'Hotsauce', 'Hummus', 'Ice cream', 'Ice cubes', 'Iceberg lettuce',
  'Icing sugar', 'Instant yeast', 'Italian fennel sausages', 'Italian seasoning', 'Jalapeno', 'Jam',
  'Jamaican curry powder', 'Jamón ibérico', 'Jasmine rice', 'Jerk', 'Jersey royal potatoes',
  'Jerusalem artichokes', 'Jumbo shrimp', 'Juniper berries', 'Kabanos sausages', 'Kabse spice',
  'Kaffir lime', 'Kaffir lime leaves', 'Kale', 'Kampot pepper', 'Khus khus', 'Kidney beans',
  'Kielbasa', 'King prawns', 'Knafeh', 'Kosher salt', 'Lamb', 'Lamb fat', 'Lamb kidney', 'Lamb leg',
  'Lamb loin chops', 'Lamb mince', 'Lamb shanks', 'Lamb shoulder', 'Lamb stock', 'Lard',
  'Lasagne sheets', 'Lean minced beef', 'Lean minced steak', 'Leek', 'Lemon', 'Lemon juice',
  'Lemon zest', 'Lemongrass', 'Lemongrass stalks', 'Lemons', 'Lentils', 'Lettuce',
  'Light brown soft sugar', 'Light raisins', 'Light rum', 'Lima beans', 'Lime', 'Lime juice',
  'Lime leaves', 'Linguine pasta', 'Liquid cheese', 'Little gem lettuce', 'Lobster', 'Longan',
  'Macaroni', 'Mackerel', 'Madras paste', 'Makrut lime leaves', 'Malai', 'Malt vinegar', 'Manchego',
  'Mango', 'Maple syrup', 'Maria cookies', 'Marinated tofu', 'Marjoram', 'Mars bar', 'Marzipan',
  'Mascarpone', 'Massaman curry paste', 'Mature cheddar', 'Mayonnaise', 'Medjool dates',
  'Melted butter', 'Meringue nests', 'Milk', 'Milk chocolate', 'Minced beef', 'Minced garlic',
  'Minced pork', 'Mincemeat', 'Miniature marshmallows', 'Mint', 'Mirin', 'Mixed beef cuts',
  'Mixed grain', 'Mixed peel', 'Mixed peppers', 'Mixed spice', 'Mixture powder', 'Molasses',
  'Monkfish', 'Monterey jack cheese', 'Morcilla', 'Morning glory', 'Mozzarella', 'Mozzarella balls',
  'Muffins', 'Mulukhiyah', 'Mung bean paste', 'Mung bean sprouts', 'Mung beans', 'Muscovado sugar',
  'Mushrooms', 'Mussels', 'Mustard', 'Mustard powder', 'Mustard seeds', 'Naan bread',
  'Napa cabbage', 'Natural yoghurt', 'New potatoes', 'Noodles', 'Nougatine', 'Nutella', 'Nutmeg',
  'Oatmeal', 'Oats', 'Oil', 'Olive oil', 'Onion', 'Onion salt', 'Onions', 'Orange',
  'Orange blossom water', 'Orange juice', 'Orange zest', 'Oregano', 'Oreo cream biscuits', 'Oxtail',
  'Oyster mushrooms', 'Oyster sauce', 'Oysters', 'Paccheri pasta', 'Padron peppers', 'Paella rice',
  'Pak choi', 'Palm butter', 'Palm hearts', 'Palm sugar', 'Panang curry paste', 'Panch poran',
  'Pandan leaves', 'Paneer', 'Panquehue cheese', 'Papelon', 'Pappardelle pasta', 'Paprika',
  'Parma ham', 'Parmesan', 'Parmesan cheese', 'Parmigiano-reggiano', 'Parsley', 'Parsnips',
  'Passata', 'Passion fruit pulp', 'Passionfruit', 'Pasta', 'Pastrami', 'Peach juice', 'Peaches',
  'Peanut brittle', 'Peanut butter', 'Peanut cookies', 'Peanut oil', 'Peanuts', 'Pears', 'Peas',
  'Pecan nuts', 'Pecorino', 'Penne pasta', 'Penne rigate', 'Pepper', 'Peppercorns',
  'Persian cucumber', 'Petit pois', 'Phyllo dough', 'Pickle juice', 'Pickled garlics',
  'Pickled grape leaves', 'Pickled scallion head brine', 'Pickled scallion heads',
  'Pico de gallo sauce', 'Pigs trotters', 'Pilchards', 'Pimento stuffed olives', 'Pine nuts',
  'Pineapple chunks', 'Pineapple juice', 'Pink food colouring', 'Pinto beans', 'Pistachio',
  'Pistachio paste', 'Pita bread', 'Pitted black olives', 'Pitted dates', 'Plain chocolate',
  'Plain flour', 'Plantain', 'Plum jam', 'Plum sauce', 'Plum tomatoes', 'Polish kabanos',
  'Polish sausage', 'Pomegranate', 'Pomegranate molasses', 'Poppy seeds', 'Pork', 'Pork back ribs',
  'Pork belly slices', 'Pork cheeks', 'Pork chops', 'Pork knuckle', 'Pork shoulder',
  'Pork shoulder steaks', 'Pork tenderloin', 'Porridge oats', 'Potato', 'Potato starch',
  'Potatoe buns', 'Potatoes', 'Powdered sugar', 'Prahok', 'Prawns', 'Pre-fried tequeños',
  'Pretzels', 'Prosciutto', 'Prunes', 'Puff pastry', 'Pul biber', 'Pumpkin', 'Pumpkin puree',
  'Purple sprouting broccoli', 'Queso fresco', 'Quinoa', 'Radish', 'Rainbow trout', 'Raisins',
  'Rapeseed oil', 'Ras el hanout', 'Raspberries', 'Raspberry jam', 'Raw frozen prawns',
  'Raw king prawns', 'Raw tiger prawns', 'Raw vegetables', 'Raw yucca', 'Red cabbage', 'Red chilli',
  'Red chilli flakes', 'Red chilli powder', 'Red curry paste', 'Red food colouring', 'Red onions',
  'Red pepper', 'Red pepper flakes', 'Red pepper paste', 'Red pepper sauce', 'Red potatoes',
  'Red snapper', 'Red wine', 'Red wine jelly', 'Red wine vinegar', 'Redcurrants', 'Refried beans',
  'Rhubarb', 'Rice', 'Rice flour', 'Rice flour pancakes', 'Rice krispies', 'Rice noodles',
  'Rice paper sheets', 'Rice stick noodles', 'Rice vermicelli', 'Rice vinegar', 'Rice wine',
  'Ricotta', 'Rigatoni', 'Roasted peanut', 'Roasted pepper', 'Roasted vegetables', 'Rocket',
  'Rolled oats', 'Romano pepper', 'Rose water', 'Rosemary', 'Rum', 'Runner beans', 'Russet potato',
  'Rye', 'Rye bread', 'Rye flour', 'Rye grain', 'Saffron', 'Sage', 'Sake', 'Salmon',
  'Salmon fillet', 'Salsa', 'Salsa lizano', 'Salt', 'Salt cod', 'Salted butter', 'Sardines',
  'Saskatoon berries', 'Sauerkraut', 'Sausages', 'Savoy cabbage', 'Sazon',
  'Sazon goya with azafran', 'Scallions', 'Scotch bonnet', 'Sea bass', 'Sea bass fillets',
  'Sea salt', 'Seafood stock', 'Seasoned rice vinegar', 'Seasoning', 'Seeds', 'Self-raising flour',
  'Semi-skimmed milk', 'Semolina', 'Semolina flour', 'Serrano ham', 'Sesame seed',
  'Sesame seed burger buns', 'Sesame seed oil', 'Sevaiiya', 'Shallots', 'Shaoxing wine', 'Shatkora',
  'Shelled hazelnuts', 'Sherry', 'Sherry vinegar', 'Shiitake mushrooms', 'Shortcrust pastry',
  'Shortening', 'Shredded coconut', 'Shredded meat', 'Shredded mexican cheese', 'Shrimp',
  'Shrimp paste', 'Shrimp stock', 'Sichuan pepper', 'Silken tofu', 'Single cream', 'Sirloin steak',
  'Sirloin steak tips', 'Sirop de liège', 'Skirty steak', 'Small potatoes', 'Smoked haddock',
  'Smoked ham', 'Smoked paprika', 'Smoked salmon', 'Smoked turkey neck', 'Smoky aïoli',
  'Smoky paprika', 'Snapper fish', 'Snow peas', 'Soda water', 'Sorrel jam', 'Sour cream',
  'Sour milk', 'Sour pork sausage', 'Soured cream and chive dip', 'Soy sauce', 'Soya bean',
  'Soya milk', 'Spaghetti', 'Speculaas spice mix', 'Spinach', 'Split peas', 'Spring onion',
  'Spring onions', 'Squash', 'Squid', 'Sriracha', 'Stale bread', 'Star anise', 'Starch',
  'Sticky rice flour', 'Stilton cheese', 'Stir-fry vegetables', 'Stoned dates', 'Stout',
  'Strained yoghurt', 'Strawberries', 'Streaky bacon', 'Strong white bread flour',
  'Strong white flour', 'Strong wholemeal flour', 'Suet', 'Sugar', 'Sugar snap peas', 'Sugar syrup',
  'Sultanas', 'Sumac', 'Summer savoury', 'Sun-dried tomatoes', 'Sunflower oil', 'Sushi rice',
  'Swede', 'Sweet chilli sauce', 'Sweet peppadew peppers', 'Sweet potato', 'Sweet potatoes',
  'Sweet quark', 'Sweet red peppers', 'Sweet sherry', 'Sweet smoked paprika', 'Sweetcorn',
  'Sweetened condensed milk', 'Swiss cheese', 'Szechuan peppercorns', 'Tabasco sauce',
  'Tagliatelle', 'Tahini', 'Tahini paste', 'Tamarind ball', 'Tamarind paste', 'Tamarind pulp',
  'Tapioca', 'Taro', 'Tarragon leaves', 'Tempeh', 'Tempura flour', 'Thai chilli jam',
  'Thai fish sauce', 'Thai green curry paste', 'Thai red curry paste', 'Thyme', 'Tiger prawns',
  'Tinned tomatos', 'Toast', 'Tobasco sauce', 'Toffee popcorn', 'Tofu', 'Tomato', 'Tomato ketchup',
  'Tomato puree', 'Tomato sauce', 'Tomatoes', 'Toor dal', 'Tortillas', 'Treacle', 'Tripe', 'Trout',
  'Truffle oil', 'Tuna', 'Turkey', 'Turkey ham', 'Turkey mince', 'Turkey neck', 'Turkish delight',
  'Turmeric', 'Turmeric powder', 'Turnips', 'Udon noodles', 'Unflavoured gelatin',
  'Unsalted beef stock', 'Unsalted butter', 'Unsalted peanuts', 'Unsalted pistachio',
  'Unsweetened cocoa', 'Unsweetened coconut milk', 'Unwaxed lemon', 'Unwaxed lime', 'Vanilla',
  'Vanilla bean paste', 'Vanilla custard', 'Vanilla extract', 'Vanilla pod', 'Vanilla powder',
  'Vanilla sugar', 'Västerbottensost cheese', 'Veal', 'Vegan butter', 'Vegan white wine vinegar',
  'Vegetable millk', 'Vegetable oil', 'Vegetable shortening', 'Vegetable stock',
  'Vegetable stock cube', 'Vegetables', 'Vermicelli pasta', 'Vermicelli rice noodles',
  'Vinaigrette dressing', 'Vine leaves', 'Vine tomatoes', 'Vinegar', 'Walnuts', 'Warm water',
  'Water', 'Water chestnut', 'Wheat flour', 'Whipping cream', 'White asparagus', 'White bread',
  'White bread mix', 'White cabbage', 'White chocolate', 'White chocolate chips', 'White cornmeal',
  'White fish', 'White fish fillets', 'White flour', 'White masarepa', 'White sauerkraut',
  'White vinegar', 'White wine', 'White wine vinegar', 'White yam', 'Whole black peppercorns',
  'Whole milk', 'Whole wheat', 'Wholegrain bread', 'Wholegrain mustard', 'Wild garlic leaves',
  'Wild mushrooms', 'Wonton skin', 'Wood ear mushrooms', 'Worcestershire sauce', 'Yautia', 'Yeast',
  'Yellow food colouring', 'Yellow masarepa', 'Yellow onion', 'Yellow pepper', 'Yellow split peas',
  'Yoghurt', 'Yogurt', 'Yuca', 'Yukon gold potatoes', 'Zapallo squash', 'Zucchini',
];
